__base__:
    - ../../default_runtime.yaml
    - ../../datasets/coco_dna/coco_dna_detection.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/faster-rcnn/faster-rcnn_r50_fpn.yaml

model:
    init_args:
        model:
            init_args:
                roi_head:
                    bbox_head:
                        num_classes: 1

data:
    init_args:
        dataloader_cfg:
            train:
                batch_size: 8
