__base__:
    - ../../default_runtime.yaml
    - ../../datasets/cholec/cholec_segmentation_train_detection.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/cascade-mask-rcnn/cascade-mask-rcnn_r50_fpn_detection.yaml

model:
    init_args:
        model:
            class_path: models.models.two_stage_predict_ellipse_segmentation.TwoStagePredictEllipseSegmentationDetector
            init_args:
                roi_head:
                    bbox_head:
                        change_items:
                            - - 0
                              - num_classes: 13
                            - - 1
                              - num_classes: 13
                            - - 2
                              - num_classes: 13

data:
    init_args:
        dataloader_cfg:
            train:
                batch_size: 8
