__base__:
    - ../../default_runtime.yaml
    - ../../datasets/isic/isic_detection_predict_rotate.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/cascade-mask-rcnn/cascade-mask-rcnn_r50_fpn_detection.yaml

model:
    class_path: models.GeneratePesudeDetectionAnnotation
    init_args:
        rotated_ann_paths: [annotations, rotated_annotations_cascade-mask-rcnn]
        model:
            init_args:
                roi_head:
                    bbox_head:
                        change_items:
                            - - 0
                              - num_classes: 1
                            - - 1
                              - num_classes: 1
                            - - 2
                              - num_classes: 1

data:
    init_args:
        dataloader_cfg:
            train:
                batch_size: 8
