__base__: sisvse_segmentation_train_detection.yaml

data:
    init_args:
        dataset_cfg:
            train:
                class_path: datasets.datasets.rotated_coco_dataset.RotatedCocoAugAnnDataset
                init_args:
                    rotated_ann_paths: [instance_jsons, rotated_instance_jsons]
                    pipeline:
                        insert_item:
                            - [1, type: mmdet.RotateImage]
