__base__:
    - ../../default_runtime.yaml
    - ../../datasets/cholec/cholec_segmentation.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/condinst/condinst_r50_fpn.yaml

model:
    init_args:
        model:
            init_args:
                bbox_head:
                    num_classes: 13
        visualizer_kwargs:
            draw_gt: false
