__base__:
    - ../../default_runtime.yaml
    - ../../datasets/nuclei/nuclei_detection_predict_rotate.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/dino/dino-4scale_r50.yaml

model:
    class_path: models.GeneratePesudeDetectionAnnotation
    init_args:
        rotated_ann_paths: [annotations, rotated_annotations_dino]
        model:
            init_args:
                bbox_head:
                    num_classes: 1
