__base__:
    - ../../default_runtime.yaml
    - ../../datasets/sisvse/sisvse_segmentation_train_detection.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/dino/dino-4scale_r50.yaml

model:
    init_args:
        model:
            class_path: models.models.dino_predict_ellipse_segmentation.DINOPredictEllipseSegmentationDetector
            init_args:
                bbox_head:
                    num_classes: 31
