__base__:
    - ../../default_runtime.yaml
    - ../../datasets/sisvse/sisvse_segmentation_train_detection.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/boxinst/boxinst_r50_fpn.yaml

model:
    init_args:
        model:
            init_args:
                bbox_head:
                    num_classes: 31
