__base__:
    - ../../default_runtime.yaml
    - ../../datasets/isic/isic_segmentation_train_rotate_feature.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/boxinst/rotate_boxinst_r50_fpn.yaml

model:
    init_args:
        model:
            init_args:
                bbox_head:
                    num_classes: 1
