__base__:
    - ../../default_runtime.yaml
    - ../../datasets/nuclei/nuclei_segmentation_train_rotate_image.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/boxinst/boxinst_r50_fpn.yaml

model:
    init_args:
        model:
            init_args:
                bbox_head:
                    num_classes: 1
