__base__: nuclei_detection.yaml

data:
    init_args:
        evaluator_cfg:
            train:
                init_args:
                    metrics:
                        metric: segm
        dataset_cfg:
            train:
                init_args:
                    pipeline:
                        change_item:
                            - - 1
                              - with_mask: true
            val:
                init_args:
                    pipeline:
                        change_item:
                            - - 1
                              - with_mask: true
        dataloader_cfg:
            train:
                batch_size: 1
            val:
                batch_size: 1

trainer:
    accumulate_grad_batches: 2
    callbacks:
        change_item:
            - - 0
              - init_args:
                    monitor: val/coco/segm_mAP_50
                    filename: "epoch:{epoch}-val_map_50:{val/coco/segm_mAP_50:.4g}"
                    mode: max
