__base__: livecell_segmentation_train_detection.yaml

data:
    init_args:
        dataset_cfg:
            train:
                class_path: datasets.datasets.rotated_coco_dataset.RotatedCocoAugAnnDataset
                init_args:
                    theta: 5
                    pipeline:
                        insert_item:
                            - [1, type: mmdet.RotateImage]
