__base__: livecell_detection.yaml

data:
    init_args:
        evaluator_cfg:
            val:
                init_args:
                    metrics:
                        metric: segm
        dataset_cfg:
            train:
                class_path: datasets.datasets.rotated_coco_dataset.RotatedCocoDataset
                init_args:
                    pipeline:
                        insert_item:
                            - [1, type: mmdet.RotateImage]
            val:
                class_path: mmdet.datasets.coco.CocoDataset
                init_args:
                    pipeline:
                        change_item:
                            - - 1
                              - with_mask: true

trainer:
    callbacks:
        change_item:
            - - 0
              - init_args:
                    monitor: val/coco/segm_mAP_50
                    filename: "epoch:{epoch}-val_map_50:{val/coco/segm_mAP_50:.4g}"
                    mode: max
