__base__: livecell_detection.yaml

data:
    init_args:
        dataset_cfg:
            predict:
                class_path: datasets.datasets.rotated_coco_dataset.RotatedCocoDataset
                init_args:
                    add_origin: false
                    pipeline:
                        insert_item:
                            - [1, type: mmdet.RotateImage]
                        change_item:
                            - - -1
                              - meta_keys:
                                    post_item: theta
