__base__: coco_dna_detection.yaml

data:
    init_args:
        evaluator_cfg:
            train:
                init_args:
                    metrics:
                        metric: segm
        dataset_cfg:
            train:
                init_args:
                    pipeline:
                        change_item:
                            - - 1
                              - with_mask: true

trainer:
    callbacks:
        change_item:
            - - 0
              - init_args:
                    monitor: val/coco/segm_mAP_50
                    filename: "epoch:{epoch}-val_map_50:{val/coco/segm_mAP_50:.4g}"
                    mode: max
