__base__:
    - ../../default_runtime.yaml
    - ../../datasets/coco_dna/coco_dna_detection_predict_rotate.yaml
    - ../../schedules/schedule_2x.yaml
    - ../../models/mask-rcnn/mask-rcnn_r50_fpn.yaml

model:
    init_args:
        model:
            init_args:
                roi_head:
                    bbox_head:
                        num_classes: 1
